// Registre des modèles de CV canadiens (CAN-STD-01 à 21, CAN-ATS-01 à 20).
// Chaque modèle n'est qu'une configuration : le rendu est fait par un
// moteur unique (src/components/cv/canada/CanadaCv.tsx) qui applique
// l'ordre officiel des sections, masque les sections vides et impose les
// règles ATS. Une simple recoloration ne constitue jamais un nouveau
// modèle : chaque configuration change la disposition ou la typographie.

export type CanadaFamily = "corporate" | "modern" | "executive" | "ats";

export interface CanadaModel {
  id: string; // ex. "CAN-STD-01"
  name: string;
  category: "CANADA" | "CANADA_ATS";
  family: CanadaFamily;
  description: string;
  /** Une colonne, ou colonne secondaire (coordonnées, compétences, langues). */
  layout:
    | { columns: "single" }
    /** headerFull : nom et titre sur toute la largeur, au-dessus des deux colonnes. */
    | { columns: "sidebar"; side: "left" | "right"; width: number; tinted: boolean; headerFull?: boolean };
  header: {
    align: "left" | "center" | "split";
    /** Coordonnées sur une ligne, ou une par ligne. */
    contacts: "inline" | "stacked";
    rule: "none" | "thin" | "thick";
    /** Petit trait coloré sous le titre professionnel. */
    accentMark?: boolean;
    /** En-tête sur un fond teinté, ou sur un bandeau foncé (couleur d'accent, texte blanc). */
    band?: boolean | "dark";
    /** Titre professionnel en gras. */
    titleBold?: boolean;
    /** Coordonnées placées sous la ligne de séparation de l'en-tête. */
    contactsBelowRule?: boolean;
    /** En-tête en deux zones : coordonnées alignées à droite. */
    contactsRight?: boolean;
  };
  headings: { case: "upper" | "normal" | "smallcaps"; style: "plain" | "rule" | "bar" | "underline" };
  /** Position des dates : à droite du titre, dessous, avant le titre, à la suite de
   * l'entreprise (« Entreprise — Lieu | dates »), ou dans une marge à gauche. */
  dates: "right" | "below" | "before" | "inline" | "margin";
  /** Expérience : entreprise en premier (lead), ou poste et entreprise sur une ligne (inline). */
  entry?: { lead?: "company"; inline?: boolean };
  skills: "inline" | "list" | "columns";
  /** Résumé mis en valeur dans un encadré teinté. */
  summaryBox?: boolean;
  type: { name: number; title: number; heading: number; body: number; headingFont: "sans" | "serif" | "grotesk" };
  density: "compact" | "normal" | "airy";
  /** Facultatifs : highlight (titre professionnel), bullet (puces des
   * réalisations), line (trait épais sous l'en-tête, accent par défaut). */
  colors: { accent: string; text: string; muted: string; rule: string; tint: string; highlight?: string; bullet?: string; line?: string };
}

export const CANADA_MODELS: CanadaModel[] = [
  {
    id: "CAN-STD-01",
    name: "Corporate Classic",
    category: "CANADA",
    family: "corporate",
    description: "Une colonne, sobre et classique : finance, administration, banque, assurance.",
    layout: { columns: "single" },
    header: { align: "left", contacts: "inline", rule: "thick" },
    headings: { case: "upper", style: "plain" },
    dates: "right",
    skills: "inline",
    type: { name: 22, title: 11.5, heading: 10, body: 9.5, headingFont: "sans" },
    density: "normal",
    colors: { accent: "#1b2f4f", text: "#1a1a1a", muted: "#5f6368", rule: "#1b2f4f", tint: "#f2f4f7" },
  },
  {
    id: "CAN-STD-02",
    name: "Corporate Sidebar",
    category: "CANADA",
    family: "corporate",
    description: "Colonne gauche teintée (coordonnées, compétences, langues), contenu principal à droite.",
    layout: { columns: "sidebar", side: "left", width: 30, tinted: true },
    header: { align: "left", contacts: "stacked", rule: "none" },
    headings: { case: "upper", style: "rule" },
    dates: "right",
    skills: "list",
    type: { name: 22, title: 11.5, heading: 10, body: 9.5, headingFont: "sans" },
    density: "normal",
    colors: { accent: "#13294b", text: "#1a1a1a", muted: "#5f6368", rule: "#c9d1dc", tint: "#eef1f5" },
  },
  {
    id: "CAN-STD-03",
    name: "Finance Executive",
    category: "CANADA",
    family: "corporate",
    description: "Une colonne, en-tête centré et filet fin : finance, banque, direction.",
    layout: { columns: "single" },
    header: { align: "center", contacts: "inline", rule: "thin" },
    headings: { case: "upper", style: "plain" },
    dates: "right",
    skills: "inline",
    type: { name: 21, title: 11, heading: 9.5, body: 9.5, headingFont: "sans" },
    density: "compact",
    colors: { accent: "#1f3a5f", text: "#141414", muted: "#4a4a4a", rule: "#2b2b2b", tint: "#f3f3f3" },
  },
  {
    id: "CAN-STD-04",
    name: "Administrative Professional",
    category: "CANADA",
    family: "corporate",
    description: "En-tête en deux zones (nom à gauche, coordonnées à droite), compétences sur deux colonnes.",
    layout: { columns: "single" },
    header: { align: "split", contacts: "stacked", rule: "thin" },
    headings: { case: "normal", style: "rule" },
    dates: "right",
    skills: "columns",
    type: { name: 21, title: 11, heading: 10.5, body: 9.5, headingFont: "sans" },
    density: "compact",
    colors: { accent: "#3d4f66", text: "#1a1a1a", muted: "#5b6573", rule: "#c3cad4", tint: "#eef1f4" },
  },
  {
    id: "CAN-STD-05",
    name: "Corporate Timeline",
    category: "CANADA",
    family: "corporate",
    description: "Chronologie typographique : les dates occupent une marge à gauche, le contenu est à droite.",
    layout: { columns: "single" },
    header: { align: "left", contacts: "inline", rule: "thin" },
    headings: { case: "upper", style: "plain" },
    dates: "margin",
    skills: "inline",
    type: { name: 21, title: 11, heading: 10, body: 9.5, headingFont: "sans" },
    density: "normal",
    colors: { accent: "#17365d", text: "#1a1a1a", muted: "#666b73", rule: "#b9c2cf", tint: "#f1f4f8" },
  },
  {
    id: "CAN-STD-06",
    name: "Business Minimal",
    category: "CANADA",
    family: "corporate",
    description: "Minimaliste et premium : nom très visible, blanc maîtrisé, filets très fins, petite touche de bleu.",
    layout: { columns: "single" },
    header: { align: "left", contacts: "inline", rule: "none" },
    headings: { case: "normal", style: "rule" },
    dates: "right",
    skills: "inline",
    type: { name: 24, title: 11.5, heading: 10, body: 9.5, headingFont: "sans" },
    density: "normal",
    colors: { accent: "#111111", text: "#111111", muted: "#6b6b6b", rule: "#e2e2e2", tint: "#f5f5f5", highlight: "#2563eb" },
  },
  {
    id: "CAN-STD-07",
    name: "Corporate Structured",
    category: "CANADA",
    family: "corporate",
    description: "En-tête pleine largeur, colonne principale à gauche, colonne droite (coordonnées, compétences, langues) séparée par un filet.",
    layout: { columns: "sidebar", side: "right", width: 31, tinted: false, headerFull: true },
    header: { align: "left", contacts: "inline", rule: "thick" },
    headings: { case: "upper", style: "plain" },
    dates: "below",
    skills: "list",
    type: { name: 22, title: 11.5, heading: 10, body: 9.5, headingFont: "sans" },
    density: "normal",
    colors: { accent: "#0f4c5c", text: "#1a1a1a", muted: "#5d6b70", rule: "#c9d6d9", tint: "#eef4f5" },
  },
  {
    id: "CAN-STD-08",
    name: "Modern Accent",
    category: "CANADA",
    family: "modern",
    description: "Une colonne moderne : trait coloré sous le titre, titres de sections avec accent vertical.",
    layout: { columns: "single" },
    header: { align: "left", contacts: "inline", rule: "none", accentMark: true },
    headings: { case: "normal", style: "bar" },
    dates: "right",
    skills: "columns",
    type: { name: 22, title: 11.5, heading: 10.5, body: 9.5, headingFont: "sans" },
    density: "normal",
    colors: { accent: "#1d4ed8", text: "#111111", muted: "#5b5b5b", rule: "#dbe3f5", tint: "#eef2ff" },
  },
  {
    id: "CAN-STD-09",
    name: "Digital Professional",
    category: "CANADA",
    family: "modern",
    description: "En-tête pleine largeur, colonne droite teintée (coordonnées, compétences, langues) : tech, digital, marketing.",
    layout: { columns: "sidebar", side: "right", width: 33, tinted: true, headerFull: true },
    header: { align: "left", contacts: "inline", rule: "none", accentMark: true },
    headings: { case: "normal", style: "plain" },
    dates: "right",
    skills: "list",
    type: { name: 22, title: 11.5, heading: 11, body: 9.5, headingFont: "sans" },
    density: "normal",
    colors: { accent: "#4338ca", text: "#16151f", muted: "#5d5b6b", rule: "#dcdbe8", tint: "#f1f1f6" },
  },
  {
    id: "CAN-STD-10",
    name: "Modern Grid",
    category: "CANADA",
    family: "modern",
    description: "En-tête sur fond teinté en deux zones (nom à gauche, coordonnées à droite), compétences sur deux colonnes.",
    layout: { columns: "single" },
    header: { align: "split", contacts: "stacked", rule: "none", band: true, contactsRight: true },
    headings: { case: "upper", style: "plain" },
    dates: "right",
    skills: "columns",
    type: { name: 21, title: 11, heading: 10, body: 9.5, headingFont: "sans" },
    density: "compact",
    colors: { accent: "#0e6b6b", text: "#151515", muted: "#5a6262", rule: "#cfdcdc", tint: "#e9f2f2" },
  },
  {
    id: "CAN-STD-11",
    name: "Project Manager",
    category: "CANADA",
    family: "modern",
    description: "En-tête compact, résumé mis en valeur dans un encadré, réalisations repérées par des puces turquoise.",
    layout: { columns: "single" },
    header: { align: "left", contacts: "inline", rule: "thin" },
    headings: { case: "upper", style: "plain" },
    dates: "right",
    skills: "inline",
    summaryBox: true,
    type: { name: 20, title: 11, heading: 10, body: 9.5, headingFont: "sans" },
    density: "compact",
    colors: { accent: "#1c2f52", text: "#151515", muted: "#5b6270", rule: "#cbd2dc", tint: "#eef6f6", bullet: "#14a3a3" },
  },
  {
    id: "CAN-STD-12",
    name: "Contemporary Split",
    category: "CANADA",
    family: "modern",
    description: "En-tête pleine largeur, colonne secondaire à gauche (35 %) séparée par un filet, contenu principal à droite.",
    layout: { columns: "sidebar", side: "left", width: 35, tinted: false, headerFull: true },
    header: { align: "left", contacts: "inline", rule: "thick" },
    headings: { case: "normal", style: "rule" },
    dates: "below",
    skills: "list",
    type: { name: 22, title: 11.5, heading: 10.5, body: 9.5, headingFont: "sans" },
    density: "normal",
    colors: { accent: "#1f4d3a", text: "#161a18", muted: "#5d6661", rule: "#d3ddd8", tint: "#eef3f0" },
  },
  {
    id: "CAN-STD-13",
    name: "Tech Minimal",
    category: "CANADA",
    family: "modern",
    description: "Une colonne sobre à typographie technique, compétences en texte, aucune jauge ni graphique.",
    layout: { columns: "single" },
    header: { align: "left", contacts: "inline", rule: "none" },
    headings: { case: "normal", style: "plain" },
    dates: "right",
    skills: "inline",
    type: { name: 23, title: 11.5, heading: 11, body: 9.5, headingFont: "grotesk" },
    density: "normal",
    colors: { accent: "#111111", text: "#151515", muted: "#5f5f5f", rule: "#e3e3e3", tint: "#f4f4f4", highlight: "#0a66ff" },
  },
  {
    id: "CAN-STD-14",
    name: "Modern Horizon",
    category: "CANADA",
    family: "modern",
    description: "En-tête en deux zones (coordonnées alignées à droite) souligné d'une ligne bleu clair, une colonne.",
    layout: { columns: "single" },
    header: { align: "split", contacts: "stacked", rule: "thick", contactsRight: true },
    headings: { case: "upper", style: "rule" },
    dates: "right",
    skills: "columns",
    type: { name: 21, title: 11, heading: 10, body: 9.5, headingFont: "sans" },
    density: "compact",
    colors: { accent: "#123a6b", text: "#151a22", muted: "#5b6573", rule: "#cfdcec", tint: "#eef4fb", line: "#5aa0e6" },
  },
  {
    id: "CAN-STD-15",
    name: "Executive Signature",
    category: "CANADA",
    family: "executive",
    description: "Nom en serif centré, fine ligne dorée sous l'en-tête, sections sobres en noir et gris.",
    layout: { columns: "single" },
    header: { align: "center", contacts: "inline", rule: "thin" },
    headings: { case: "upper", style: "plain" },
    dates: "right",
    skills: "inline",
    type: { name: 23, title: 11, heading: 10, body: 9.5, headingFont: "serif" },
    density: "normal",
    colors: { accent: "#1a1a1a", text: "#1a1a1a", muted: "#5e5e5e", rule: "#b8975a", tint: "#f6f3ec" },
  },
  {
    id: "CAN-STD-16",
    name: "Executive Column",
    category: "CANADA",
    family: "executive",
    description: "Bandeau bleu nuit sur toute la largeur, colonne droite gris perle (28 %) : direction, management.",
    layout: { columns: "sidebar", side: "right", width: 28, tinted: true, headerFull: true },
    header: { align: "left", contacts: "inline", rule: "none", band: "dark" },
    headings: { case: "upper", style: "rule" },
    dates: "right",
    skills: "list",
    type: { name: 22, title: 11.5, heading: 10, body: 9.5, headingFont: "sans" },
    density: "normal",
    colors: { accent: "#14213d", text: "#1a1a1a", muted: "#5c6370", rule: "#d5d9e0", tint: "#eef0f3" },
  },
  {
    id: "CAN-STD-17",
    name: "Elegant Serif",
    category: "CANADA",
    family: "executive",
    description: "Nom et titres de sections en serif, corps de texte sans serif, touche bordeaux discrète.",
    layout: { columns: "single" },
    header: { align: "left", contacts: "inline", rule: "thin" },
    headings: { case: "normal", style: "rule" },
    dates: "right",
    skills: "inline",
    type: { name: 23, title: 11.5, heading: 11.5, body: 9.5, headingFont: "serif" },
    density: "compact",
    colors: { accent: "#6d1f2f", text: "#1a1a1a", muted: "#5f5a5b", rule: "#e2d6d8", tint: "#f7f1f2" },
  },
  {
    id: "CAN-STD-18",
    name: "Leadership Profile",
    category: "CANADA",
    family: "executive",
    description: "Nom à gauche, coordonnées à droite, résumé mis en valeur, responsabilités très lisibles.",
    layout: { columns: "single" },
    header: { align: "split", contacts: "stacked", rule: "none", contactsRight: true },
    headings: { case: "upper", style: "bar" },
    dates: "right",
    skills: "columns",
    summaryBox: true,
    type: { name: 22, title: 11.5, heading: 10, body: 9.5, headingFont: "sans" },
    density: "compact",
    colors: { accent: "#1b2a4a", text: "#1a1a1a", muted: "#4f5560", rule: "#d3d8e0", tint: "#f0f2f6", bullet: "#1b2a4a" },
  },
  {
    id: "CAN-STD-19",
    name: "Consultant Premium",
    category: "CANADA",
    family: "executive",
    description: "En-tête pleine largeur, colonne gauche teintée (coordonnées, compétences, langues), accents vert olive.",
    layout: { columns: "sidebar", side: "left", width: 30, tinted: true, headerFull: true },
    header: { align: "left", contacts: "inline", rule: "none", accentMark: true },
    headings: { case: "normal", style: "bar" },
    dates: "below",
    skills: "list",
    type: { name: 22, title: 11.5, heading: 11, body: 9.5, headingFont: "sans" },
    density: "normal",
    colors: { accent: "#3a3a3a", text: "#1c1c1c", muted: "#62645c", rule: "#dcdccf", tint: "#f2f2ea", highlight: "#5b6b2f" },
  },
  {
    id: "CAN-STD-20",
    name: "Executive Editorial",
    category: "CANADA",
    family: "executive",
    description: "Très grand nom, coordonnées sous une ligne, titres en petites majuscules, dates en marge latérale.",
    layout: { columns: "single" },
    header: { align: "left", contacts: "inline", rule: "thin", contactsBelowRule: true },
    headings: { case: "smallcaps", style: "plain" },
    dates: "margin",
    skills: "inline",
    type: { name: 26, title: 11.5, heading: 11, body: 9.5, headingFont: "sans" },
    density: "compact",
    colors: { accent: "#111111", text: "#151515", muted: "#5d6670", rule: "#4a6b8a", tint: "#f1f4f7", highlight: "#4a6b8a" },
  },
  {
    id: "CAN-STD-21",
    name: "International Executive",
    category: "CANADA",
    family: "executive",
    description: "Nom et titre centrés, compétences sur deux colonnes, chaque expérience détaillée ligne par ligne.",
    layout: { columns: "single" },
    header: { align: "center", contacts: "inline", rule: "thick" },
    headings: { case: "upper", style: "plain" },
    dates: "below",
    skills: "columns",
    type: { name: 20, title: 10.5, heading: 9.5, body: 9.5, headingFont: "sans" },
    density: "compact",
    colors: { accent: "#0b2e59", text: "#161a20", muted: "#56606d", rule: "#cdd5e0", tint: "#eef2f7" },
  },
  {
    id: "CAN-ATS-01",
    name: "ATS Traditional",
    category: "CANADA_ATS",
    family: "ats",
    description: "Nom, titre et coordonnées centrés, sections en majuscules soulignées, dates à droite.",
    layout: { columns: "single" },
    header: { align: "center", contacts: "inline", rule: "none" },
    headings: { case: "upper", style: "rule" },
    dates: "right",
    skills: "inline",
    type: { name: 20, title: 11, heading: 10.5, body: 9.5, headingFont: "sans" },
    density: "normal",
    colors: { accent: "#111111", text: "#111111", muted: "#444444", rule: "#9a9a9a", tint: "#ffffff" },
  },
  {
    id: "CAN-ATS-02",
    name: "ATS Standard",
    category: "CANADA_ATS",
    family: "ats",
    description: "Nom à gauche, coordonnées sur une ligne, titres en gras, dates sous l'entreprise.",
    layout: { columns: "single" },
    header: { align: "left", contacts: "inline", rule: "none" },
    headings: { case: "normal", style: "plain" },
    dates: "below",
    skills: "inline",
    type: { name: 20, title: 11, heading: 11, body: 9.5, headingFont: "sans" },
    density: "compact",
    colors: { accent: "#111111", text: "#111111", muted: "#444444", rule: "#9a9a9a", tint: "#ffffff" },
  },
  {
    id: "CAN-ATS-03",
    name: "ATS Formal",
    category: "CANADA_ATS",
    family: "ats",
    description: "Nom et coordonnées centrés, titres de sections soulignés, dates à droite.",
    layout: { columns: "single" },
    header: { align: "center", contacts: "inline", rule: "none" },
    headings: { case: "normal", style: "underline" },
    dates: "right",
    skills: "inline",
    type: { name: 20, title: 11, heading: 11, body: 9.5, headingFont: "sans" },
    density: "normal",
    colors: { accent: "#111111", text: "#111111", muted: "#444444", rule: "#9a9a9a", tint: "#ffffff" },
  },
  {
    id: "CAN-ATS-04",
    name: "ATS Professional",
    category: "CANADA_ATS",
    family: "ats",
    description: "Nom à gauche, titres en majuscules soulignés d'une ligne fine, dates sous l'entreprise.",
    layout: { columns: "single" },
    header: { align: "left", contacts: "inline", rule: "none" },
    headings: { case: "upper", style: "rule" },
    dates: "below",
    skills: "inline",
    type: { name: 20, title: 11, heading: 10, body: 9.5, headingFont: "sans" },
    density: "compact",
    colors: { accent: "#111111", text: "#111111", muted: "#444444", rule: "#b5b5b5", tint: "#ffffff" },
  },
  {
    id: "CAN-ATS-05",
    name: "ATS Conventional",
    category: "CANADA_ATS",
    family: "ats",
    description: "En-tête centré, sections à gauche, dates placées avant chaque poste.",
    layout: { columns: "single" },
    header: { align: "center", contacts: "inline", rule: "none" },
    headings: { case: "upper", style: "plain" },
    dates: "before",
    skills: "inline",
    type: { name: 20, title: 11, heading: 10.5, body: 9.5, headingFont: "sans" },
    density: "compact",
    colors: { accent: "#111111", text: "#111111", muted: "#444444", rule: "#9a9a9a", tint: "#ffffff" },
  },
  {
    id: "CAN-ATS-06",
    name: "ATS Modern Clean",
    category: "CANADA_ATS",
    family: "ats",
    description: "Grand nom à gauche, titres en gras, espacement généreux, dates à droite.",
    layout: { columns: "single" },
    header: { align: "left", contacts: "inline", rule: "none" },
    headings: { case: "normal", style: "plain" },
    dates: "right",
    skills: "inline",
    type: { name: 24, title: 11.5, heading: 11, body: 9.5, headingFont: "sans" },
    density: "airy",
    colors: { accent: "#111111", text: "#111111", muted: "#444444", rule: "#9a9a9a", tint: "#ffffff" },
  },
  {
    id: "CAN-ATS-07",
    name: "ATS Contemporary",
    category: "CANADA_ATS",
    family: "ats",
    description: "Ligne fine sous l'en-tête, sections en majuscules, dates sur une ligne distincte.",
    layout: { columns: "single" },
    header: { align: "left", contacts: "inline", rule: "thin" },
    headings: { case: "upper", style: "plain" },
    dates: "below",
    skills: "inline",
    type: { name: 20, title: 11, heading: 10.5, body: 9.5, headingFont: "sans" },
    density: "compact",
    colors: { accent: "#111111", text: "#111111", muted: "#444444", rule: "#8a8a8a", tint: "#ffffff" },
  },
  {
    id: "CAN-ATS-08",
    name: "ATS Balanced",
    category: "CANADA_ATS",
    family: "ats",
    description: "En-tête centré souligné, sections à gauche avec séparateurs fins, dates à droite.",
    layout: { columns: "single" },
    header: { align: "center", contacts: "inline", rule: "thin" },
    headings: { case: "normal", style: "rule" },
    dates: "right",
    skills: "inline",
    type: { name: 20, title: 11, heading: 11, body: 9.5, headingFont: "sans" },
    density: "compact",
    colors: { accent: "#111111", text: "#111111", muted: "#444444", rule: "#b5b5b5", tint: "#ffffff" },
  },
  {
    id: "CAN-ATS-09",
    name: "ATS Linear",
    category: "CANADA_ATS",
    family: "ats",
    description: "Nom à gauche, titres soulignés, chaque expérience en bloc vertical : poste, entreprise, lieu, dates.",
    layout: { columns: "single" },
    header: { align: "left", contacts: "inline", rule: "none" },
    headings: { case: "upper", style: "underline" },
    dates: "below",
    skills: "inline",
    type: { name: 20, title: 11, heading: 10.5, body: 9.5, headingFont: "sans" },
    density: "compact",
    colors: { accent: "#111111", text: "#111111", muted: "#444444", rule: "#9a9a9a", tint: "#ffffff" },
  },
  {
    id: "CAN-ATS-10",
    name: "ATS Modern Professional",
    category: "CANADA_ATS",
    family: "ats",
    description: "Grand nom, ligne fine sous l'en-tête, sections en gras bien espacées, dates à droite.",
    layout: { columns: "single" },
    header: { align: "left", contacts: "inline", rule: "thin" },
    headings: { case: "upper", style: "plain" },
    dates: "right",
    skills: "inline",
    type: { name: 24, title: 11.5, heading: 10.5, body: 9.5, headingFont: "sans" },
    density: "normal",
    colors: { accent: "#111111", text: "#111111", muted: "#444444", rule: "#9a9a9a", tint: "#ffffff" },
  },
  {
    id: "CAN-ATS-11",
    name: "ATS Executive Classic",
    category: "CANADA_ATS",
    family: "ats",
    description: "En-tête centré, nom et titres de sections en serif, sections en majuscules soulignées, dates à droite.",
    layout: { columns: "single" },
    header: { align: "center", contacts: "inline", rule: "none" },
    headings: { case: "upper", style: "rule" },
    dates: "right",
    skills: "inline",
    type: { name: 21, title: 11, heading: 10.5, body: 9.5, headingFont: "serif" },
    density: "normal",
    colors: { accent: "#111111", text: "#111111", muted: "#444444", rule: "#9a9a9a", tint: "#ffffff" },
  },
  {
    id: "CAN-ATS-12",
    name: "ATS Leadership",
    category: "CANADA_ATS",
    family: "ats",
    description: "Titre professionnel en gras, poste en première ligne, entreprise, lieu et dates en deuxième ligne.",
    layout: { columns: "single" },
    header: { align: "left", contacts: "inline", rule: "thin", titleBold: true },
    headings: { case: "normal", style: "plain" },
    dates: "inline",
    skills: "inline",
    type: { name: 21, title: 11.5, heading: 11, body: 9.5, headingFont: "sans" },
    density: "normal",
    colors: { accent: "#111111", text: "#111111", muted: "#444444", rule: "#b5b5b5", tint: "#ffffff" },
  },
  {
    id: "CAN-ATS-13",
    name: "ATS Senior Professional",
    category: "CANADA_ATS",
    family: "ats",
    description: "En-tête centré, sections en petites capitales avec séparateurs fins, entreprise en gras puis poste.",
    layout: { columns: "single" },
    header: { align: "center", contacts: "inline", rule: "none" },
    headings: { case: "upper", style: "rule" },
    dates: "right",
    entry: { lead: "company" },
    skills: "inline",
    type: { name: 20, title: 11, heading: 9.5, body: 9.5, headingFont: "sans" },
    density: "normal",
    colors: { accent: "#111111", text: "#111111", muted: "#444444", rule: "#b5b5b5", tint: "#ffffff" },
  },
  {
    id: "CAN-ATS-14",
    name: "ATS Executive Minimal",
    category: "CANADA_ATS",
    family: "ats",
    description: "Nom à gauche en typographie nette, titres en gras sans soulignement, dates sous les intitulés.",
    layout: { columns: "single" },
    header: { align: "left", contacts: "inline", rule: "none" },
    headings: { case: "normal", style: "plain" },
    dates: "below",
    skills: "inline",
    type: { name: 22, title: 11, heading: 11.5, body: 9.5, headingFont: "grotesk" },
    density: "compact",
    colors: { accent: "#111111", text: "#111111", muted: "#444444", rule: "#9a9a9a", tint: "#ffffff" },
  },
  {
    id: "CAN-ATS-15",
    name: "ATS Management",
    category: "CANADA_ATS",
    family: "ats",
    description: "En-tête centré, sections soulignées d'une ligne, poste en gras, entreprise et lieu dessous, dates distinctes.",
    layout: { columns: "single" },
    header: { align: "center", contacts: "inline", rule: "none" },
    headings: { case: "upper", style: "rule" },
    dates: "below",
    skills: "inline",
    type: { name: 20, title: 11, heading: 10, body: 9.5, headingFont: "sans" },
    density: "compact",
    colors: { accent: "#111111", text: "#111111", muted: "#444444", rule: "#8a8a8a", tint: "#ffffff" },
  },
  {
    id: "CAN-ATS-16",
    name: "ATS Compact Classic",
    category: "CANADA_ATS",
    family: "ats",
    description: "Espacement réduit, poste et entreprise sur une ligne, dates à droite.",
    layout: { columns: "single" },
    header: { align: "left", contacts: "inline", rule: "none" },
    headings: { case: "normal", style: "plain" },
    dates: "right",
    entry: { inline: true },
    skills: "inline",
    type: { name: 20, title: 11, heading: 11, body: 9.5, headingFont: "sans" },
    density: "compact",
    colors: { accent: "#111111", text: "#111111", muted: "#444444", rule: "#9a9a9a", tint: "#ffffff" },
  },
  {
    id: "CAN-ATS-17",
    name: "ATS Dense Professional",
    category: "CANADA_ATS",
    family: "ats",
    description: "En-tête centré, sections en majuscules, poste en gras puis entreprise et dates sur la ligne suivante.",
    layout: { columns: "single" },
    header: { align: "center", contacts: "inline", rule: "none" },
    headings: { case: "upper", style: "plain" },
    dates: "inline",
    skills: "inline",
    type: { name: 20, title: 11, heading: 10, body: 9.5, headingFont: "sans" },
    density: "compact",
    colors: { accent: "#111111", text: "#111111", muted: "#444444", rule: "#9a9a9a", tint: "#ffffff" },
  },
  {
    id: "CAN-ATS-18",
    name: "ATS Space Saver",
    category: "CANADA_ATS",
    family: "ats",
    description: "Sections légèrement soulignées, poste sur une ligne, entreprise et dates sur la suivante.",
    layout: { columns: "single" },
    header: { align: "left", contacts: "inline", rule: "none" },
    headings: { case: "normal", style: "rule" },
    dates: "inline",
    skills: "inline",
    type: { name: 20, title: 11, heading: 10.5, body: 9.5, headingFont: "sans" },
    density: "compact",
    colors: { accent: "#111111", text: "#111111", muted: "#444444", rule: "#d0d0d0", tint: "#ffffff" },
  },
  {
    id: "CAN-ATS-19",
    name: "ATS Compact Modern",
    category: "CANADA_ATS",
    family: "ats",
    description: "Grand nom, en-tête très compact, poste et entreprise sur une ligne, dates sur la ligne suivante.",
    layout: { columns: "single" },
    header: { align: "left", contacts: "inline", rule: "none" },
    headings: { case: "normal", style: "plain" },
    dates: "below",
    entry: { inline: true },
    skills: "inline",
    type: { name: 24, title: 11, heading: 11, body: 9.5, headingFont: "sans" },
    density: "compact",
    colors: { accent: "#111111", text: "#111111", muted: "#444444", rule: "#9a9a9a", tint: "#ffffff" },
  },
  {
    id: "CAN-ATS-20",
    name: "ATS One Page",
    category: "CANADA_ATS",
    family: "ats",
    description: "Ligne fine sous l'en-tête, sections en majuscules, poste et entreprise sur une ligne, dates à droite.",
    layout: { columns: "single" },
    header: { align: "left", contacts: "inline", rule: "thin" },
    headings: { case: "upper", style: "plain" },
    dates: "right",
    entry: { inline: true },
    skills: "inline",
    type: { name: 20, title: 11, heading: 10, body: 9.5, headingFont: "sans" },
    density: "compact",
    colors: { accent: "#111111", text: "#111111", muted: "#444444", rule: "#9a9a9a", tint: "#ffffff" },
  },
];

export const canadaModelById = (id: string) => CANADA_MODELS.find((m) => m.id === id);
